version: '3'
services: 
  web:
    container_name: ecommerceapp
    restart: always
    build: .
    env_file:
      - ./.env
    ports:
      - "5000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"