const express = require('express')
const productRouter = require('./routes/productRoutes')
const dbConnect = require('./config/dbConnect')
const app = express()
const morgan = require('morgan')
const config = require('./config/config')
const cookieParser = require('cookie-parser')
const {errorHandler, notFound } = require('./middleware/errorHandler')
console.log(process.env.PORT);
const PORT = process.env.PORT || 3000
const authRouter = require('./routes/authRoutes')
const blogRouter = require('./routes/blogRoutes')
const categoryRouter = require('./routes/categoryRoutes')
const blogCategoryRouter = require('./routes/blogCategoryRoutes')
const brandRouter = require('./routes/brandRoutes')
const couponRouter = require('./routes/couponRoutes')
const multer = require('multer')
app.use(express.json())
app.use(cookieParser())
app.use(morgan())
dbConnect()
app.use("/api/user", authRouter)
app.use("/api/product", productRouter)
app.use("/api/blog", blogRouter)
app.use("/api/category", categoryRouter)
app.use("/api/blogcategory", blogCategoryRouter)
app.use("/api/brand", brandRouter)
app.use("/api/coupon", couponRouter)
app.use(multer)
app.use(notFound)
app.use(errorHandler)
app.listen(config.PORT, () => {
    console.log(`Server is running in port: ${PORT}`);
})
